# Generated by Django 2.1.5 on 2019-02-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isIDFSent',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='isRSDFSent',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='logged_in_time',
            field=models.DateTimeField(null=True),
        ),
    ]
