# Generated by Django 2.1 on 2018-10-04 18:04

from django.db import migrations, models
import django.db.models.deletion
import util.types


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='Student Photo', upload_to=''),
        ),
        migrations.AlterField(
            model_name='batch',
            name='email_id',
            field=models.EmailField(default='invalid@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='batch',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.VMS_Session'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_city',
            field=models.CharField(blank=True, help_text='City', max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_short_url',
            field=models.URLField(blank=True, help_text='Organization Location URL'),
        ),
        migrations.AlterField(
            model_name='student',
            name='domain_key_word',
            field=models.CharField(blank=True, help_text="Student's Domain", max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_id',
            field=models.EmailField(default='invalid@example.com', help_text='Student Email ID', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='join_date',
            field=models.DateField(blank=True, help_text='Join Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor_designation',
            field=models.CharField(blank=True, default='Mentor', help_text="Mentor's Designation", max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor_email_id',
            field=models.EmailField(blank=True, default='invalid@example.com', help_text="Mentor's email ID", max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor_name',
            field=models.CharField(blank=True, help_text='Mentor', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='Student Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Organization', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(help_text='Student Phone Number', max_length=13),
        ),
        migrations.AlterField(
            model_name='student',
            name='postal_address',
            field=models.CharField(blank=True, help_text='Address', max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='project_category',
            field=models.CharField(blank=True, choices=[('Industry', 'Industry Project'), ('Research', 'Institution/Research Project')], help_text='Project Category', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='project_title',
            field=models.CharField(help_text='Project Title', max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='report_submission_status',
            field=models.CharField(choices=[('Pending', util.types.ReportSubmissionStatus('Pending')), ('Submitted', util.types.ReportSubmissionStatus('Submitted'))], default=('Pending', util.types.ReportSubmissionStatus('Pending')), help_text='Report Submission status', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(choices=[(7, '7'), (9, '9'), (4, '4')], help_text='Semester'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pass',
            field=models.CharField(help_text='Passcode', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Administrator', util.types.UserRoles('Administrator')), ('Viva Coordinator', util.types.UserRoles('Viva Coordinator')), ('Tutor', util.types.UserRoles('Tutor')), ('Guide', util.types.UserRoles('Guide')), ('Guest', util.types.UserRoles('Guest'))], help_text='User role', max_length=50),
        ),
    ]
