# Generated by Django 2.1 on 2019-01-30 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0002_auto_20181004_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='join_date',
            field=models.DateField(default=datetime.date.today, help_text='Join Date'),
        ),
    ]
