# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-01 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0003_auto_20170101_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set([('session', 'course')]),
        ),
    ]
