# Generated by Django 2.1.5 on 2019-02-01 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0004_auto_20190201_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidestudentmap',
            name='user',
            field=models.OneToOneField(default='-1', on_delete=django.db.models.deletion.CASCADE, to='VMS.User'),
        ),
    ]
