# Generated by Django 2.1.5 on 2019-02-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0005_auto_20190201_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='guidestudentmap',
            name='id',
        ),
        migrations.AlterField(
            model_name='batch',
            name='tutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='VMS.User'),
        ),
        migrations.AlterField(
            model_name='guidestudentmap',
            name='user',
            field=models.OneToOneField(default='-1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='VMS.User'),
        ),
    ]
