# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-01 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('email_id', models.EmailField(default='Invalid', max_length=254)),
                ('strength', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Batch',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(default='none', max_length=5)),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=10)),
                ('core_competency', models.CharField(max_length=30)),
                ('email_id', models.EmailField(default='Invalid', max_length=254)),
                ('areas_of_interest', models.TextField()),
                ('phone_number', models.CharField(max_length=13)),
                ('is_guide', models.BooleanField(default=False)),
                ('allocated_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='GuideStudentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.Faculty')),
            ],
            options={
                'db_table': 'GuideStudentMap',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('semester', models.IntegerField(choices=[(7, '7'), (9, '9'), (4, '4')])),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(default='Invalid', max_length=254)),
                ('phone_number', models.CharField(max_length=13)),
                ('project_category', models.CharField(blank=True, choices=[('Industry', 'Industry Project'), ('Research', 'Institution/Research Project')], max_length=20)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('postal_address', models.CharField(blank=True, max_length=500)),
                ('address_short_url', models.CharField(blank=True, max_length=200)),
                ('mentor_name', models.CharField(blank=True, max_length=100)),
                ('mentor_designation', models.CharField(blank=True, max_length=100)),
                ('mentor_email_id', models.EmailField(blank=True, max_length=254)),
                ('domain_key_word', models.CharField(blank=True, max_length=300)),
                ('project_title', models.CharField(blank=True, max_length=500)),
                ('join_date', models.CharField(blank=True, max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.Course')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.Course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.Faculty')),
            ],
            options={
                'db_table': 'Tutor',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pass', models.CharField(max_length=150)),
                ('user_role', models.IntegerField(default=-1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.Faculty')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='VMS_Session',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('session_year', models.IntegerField(default=0)),
                ('session_sem', models.CharField(choices=[('odd', 'odd'), ('even', 'even')], max_length=5)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'VMS_Session',
            },
        ),
        migrations.AddField(
            model_name='tutor',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.VMS_Session'),
        ),
        migrations.AddField(
            model_name='guidestudentmap',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.VMS_Session'),
        ),
        migrations.AddField(
            model_name='guidestudentmap',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.Student'),
        ),
        migrations.AddField(
            model_name='guidestudentmap',
            name='tutor',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='VMS.Tutor'),
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.Course'),
        ),
        migrations.AddField(
            model_name='batch',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VMS.VMS_Session'),
        ),
        migrations.AddField(
            model_name='batch',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.Faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('user_id', 'user_role')]),
        ),
        migrations.AlterUniqueTogether(
            name='tutor',
            unique_together=set([('session', 'faculty', 'course')]),
        ),
        migrations.AlterUniqueTogether(
            name='guidestudentmap',
            unique_together=set([('session', 'guide', 'student')]),
        ),
    ]
