# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0004_auto_20170101_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address_city',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
