# Generated by Django 2.1 on 2018-09-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0006_auto_20180827_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('Software Systems', 'Software Systems'), ('Theoretical Computer Science', 'Theoretical Computer Science'), ('Data Science', 'Data Science')], default=('Software Systems', 'Software Systems'), max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree_name',
            field=models.CharField(default='MSc', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_name',
            field=models.CharField(choices=[('SWS', 'SWS'), ('TCS', 'TCS'), ('DS', 'DS')], default=('SWS', 'SWS'), max_length=5),
        ),
        migrations.AlterField(
            model_name='vms_session',
            name='session_id',
            field=models.IntegerField(help_text='Session ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vms_session',
            name='session_sem',
            field=models.CharField(choices=[('odd', 'odd'), ('even', 'even')], default=('odd', 'odd'), help_text='Semester Choices', max_length=5),
        ),
        migrations.AlterField(
            model_name='vms_session',
            name='session_year',
            field=models.IntegerField(default=0, help_text='Session Year'),
        ),
    ]
